# Generated by Django 4.2.15 on 2024-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride_Thrill",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("open_state", models.BooleanField()),
                ("wait_time", models.PositiveSmallIntegerField()),
                ("last_updated", models.DateTimeField()),
            ],
        ),
    ]
