# Generated by Django 4.2.15 on 2024-08-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_rides_delete_ride_thrill"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rides",
            new_name="Ride",
        ),
    ]
