# Generated by Django 4.2.15 on 2024-09-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="type",
            new_name="category",
        ),
    ]
