name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd themepark-queues-app  # Navigate to project directory
            git fetch --all
            git reset --hard origin/main  # Hard reset to the latest commit on main
            source /env/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies if needed
            python themepark_queues/manage.py migrate  # Run migrations if necessary
            python themepark_queues/manage.py collectstatic --noinput  # Collects all static files to global location
            sudo systemctl daemon-reload  # Reload systemd
            sudo systemctl restart gunicorn  # Restart gunicorn
            sudo systemctl restart nginx  # Restart nginx
          EOF
